### ISSUE TITLE
when creating a PO it is not possible to create a new LOT nr when more then one PCE

### ISSUE THREAD

**Issue by BenisDracke** [qrtl/qrtl-addons#9]
When receiving a product in PO with more then one PCE. There is no way to create a new serial nr.
If you split the product so you can define a serial for each product you don't have the Create new in the combobox.

When only one PCE of a product in the PO you can create a new serial nr.

**Comment by yostashiro** [comment]
Thanks for the report.  I have confirmed the behavior.  Will check and see if this can be fixed when I have time.

**Comment by yostashiro** [comment]
@ittask We have fixed the issue with #12 .  Please check.
